# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjuDcNWxHei-3R_ogMBlRkO1YlhpeX-1
"""

#Instalar bibliotecas
#!pip install --upgrade google-api-python-client
#!pip install matplotlib
#!pip install pytube
#!pip install moviepy
#!pip install imageio[ffmpeg]
#!pip install git+https://github.com/openai/whisper.git
#!pip install cohere openai

from googleapiclient.discovery import build
import datetime

# Replace with your API key
api_key = 'YOUR_API_KEY_HERE'

youtube = build('youtube', 'v3', developerKey=api_key)

# Calculate the date one year ago
one_year_ago = datetime.datetime.now() - datetime.timedelta(days=365)
start_date = one_year_ago.strftime('%Y-%m-%dT%H:%M:%SZ')

# Perform the search
request = youtube.search().list(
    q='PicPay',
    part='snippet',
    maxResults=20,
    order='viewCount',
    publishedAfter=start_date,
    type='video'
)
response = request.execute()

# Iterate over each found video
for item in response.get('items', []):
    video_id = item['id']['videoId']
    title = item['snippet']['title']

    # Get video statistics and snippet
    video_request = youtube.videos().list(
        part='statistics,snippet',
        id=video_id
    )
    video_response = video_request.execute()
    video_info = video_response.get('items', [])[0]

    # Display the results
    video_stats = video_info['statistics']
    video_snippet = video_info['snippet']
    tags = video_snippet.get('tags', [])
    thumbnails = video_snippet.get('thumbnails', {})

    print(f"Title: {title}")
    print(f"Video ID: {video_id}")
    print(f"Views: {video_stats.get('viewCount')}")
    print(f"Likes: {video_stats.get('likeCount')}")
    print(f"Dislikes: {video_stats.get('dislikeCount')}")
    print(f"Comments: {video_stats.get('commentCount')}")
    print(f"Tags: {', '.join(tags) if tags else 'No tags'}")
    print(f"Thumbnails: {', '.join(thumbnails.keys())}")
    print("------")